[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rugged = "RuggedGame11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'tests run via nix flake check'"
